### ISSUE TITLE
View Scores NoneType not subscriptable

### ISSUE THREAD

**Issue by smart-patrol** [facebookresearch/vizseq#27]
When running the following for scores like Rouge and others like:

`vizseq.view_scores(ref, hypo, ['metric that's not bleu'], tags=tag)`

I am getting:
```
~/.local/lib/python3.6/site-packages/vizseq/scorers/__init__.py in _score_multiprocess_averaged(self, hypothesis, references, tags, sent_score_func)
    170             for t in tag_set:
    171                 indices = [i for i, cur in enumerate(tags) if t in cur]
--> 172                 group_scores[t] = np.mean([sent_scores[i] for i in indices])
    173 
    174         return VizSeqScore.make(

~/.local/lib/python3.6/site-packages/vizseq/scorers/__init__.py in <listcomp>(.0)
    170             for t in tag_set:
    171                 indices = [i for i, cur in enumerate(tags) if t in cur]
--> 172                 group_scores[t] = np.mean([sent_scores[i] for i in indices])
    173 
    174         return VizSeqScore.make(

TypeError: 'NoneType' object is not subscriptable
```
Any idea why that's going on? Using text data this is at least 3 tokens or more.

This works fine when running `view_examples`.

**Comment by kahne** [comment]
@smart-patrol 

Sorry for late reply and thank you very much for reporting this issue!

This bug has been fixed in #31 . Please pull the master branch and reinstall VizSeq with `pip install -e <github repo root>`. Also, a new PyPI package will be released soon (with other bug fixes). You could also `pip install --upgrade vizseq` then.

Thanks again for your support on VizSeq!
