### ISSUE TITLE
Question about `tag` and `group` in official example

### ISSUE THREAD

**Issue by YKX-A** [facebookresearch/vizseq#33]
In the official scorer example from https://facebookresearch.github.io/vizseq/docs/getting_started/scorer_example/, the second block confuse me.
```
Corpus-level BLEU: 67.945
Sentence-level BLEU: [75.984, 61.479]
Group BLEU: {'Test Group 2': 75.984, 'Test Group 1': 75.984}
```
I can see two generated sentences with corresponding reference sentences in the first block.
```
ref = [['This is a sample #1 reference.', 'This is a sample #2 reference.']]
hypo = ['This is a sample #1 prediction.', 'This is a sample #2 model prediction.']
tags = [['Test Group 1', 'Test Group 2']]
scores = scorer.score(hypo, ref, tags=tags)
print(f'Corpus-level BLEU: {scores.corpus_score}')
print(f'Sentence-level BLEU: {scores.sent_scores}')
print(f'Group BLEU: {scores.group_scores}')
```
 The first sample belongs to `Test Group 1` and the second sample belongs to `Test Group 2`. If I'm not misunderstanding the use of the `tag`, according to the `Sentence-level BLEU`,the `Group BLEU` should be `{'Test Group 2':  61.479, 'Test Group 1': 75.984}`.

But the execution result is `Group BLEU: {'Test Group 2': 75.984, 'Test Group 1': 75.984}`

**Comment by kahne** [comment]
@YKX-A 

Sentence-level BLEU and corpus-level BLEU on one single sentence are NOT the same. This is because the former one uses a different smoothing method to accommodate the sparsity of matched n-grams in a sentence. The group-level BLEU follows the calculation of the corpus-level one since it focuses on an evaluation subset but not a sentence.


References:
1. sentence-level: https://github.com/mjpost/sacrebleu/blob/master/sacrebleu/sacrebleu.py#L562
2. corpus-level: https://github.com/mjpost/sacrebleu/blob/master/sacrebleu/sacrebleu.py#L586

**Comment by YKX-A** [comment]
Thanks.
